package hung.entity;
// Generated Feb 28, 2024, 10:12:30 AM by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private BigInteger empId;
	private String empName;
	private String empNo;
	private Date hireDate;
	private byte[] image;
	private String job;
	private double salary;
	private int deptId;
	private BigInteger mngId;

	public Employee() {
	}

	public Employee(BigInteger empId, String empName, String empNo, Date hireDate, String job, double salary,
			int deptId) {
		this.empId = empId;
		this.empName = empName;
		this.empNo = empNo;
		this.hireDate = hireDate;
		this.job = job;
		this.salary = salary;
		this.deptId = deptId;
	}

	public Employee(BigInteger empId, String empName, String empNo, Date hireDate, byte[] image, String job,
			double salary, int deptId, BigInteger mngId) {
		this.empId = empId;
		this.empName = empName;
		this.empNo = empNo;
		this.hireDate = hireDate;
		this.image = image;
		this.job = job;
		this.salary = salary;
		this.deptId = deptId;
		this.mngId = mngId;
	}

	public BigInteger getEmpId() {
		return this.empId;
	}

	public void setEmpId(BigInteger empId) {
		this.empId = empId;
	}

	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	public BigInteger getMngId() {
		return this.mngId;
	}

	public void setMngId(BigInteger mngId) {
		this.mngId = mngId;
	}

}
